import 'package:flutter/widgets.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import '../../l10n/generated/app_localizations.dart';

/// Localization wiring for `GetMaterialApp`, kept in one place so adding a
/// language is a change here plus translations, not a hunt through main.dart.
///
/// App strings are moving into `lib/l10n/app_en.arb` (read through
/// `AppLocalizations.of(context)`, generated by `flutter gen-l10n`). The
/// buyer storefront, cart and shell are extracted; the rest are still
/// English literals in their widgets. Only English is listed: declaring
/// e.g. Swahili before the remaining screens are extracted would give
/// Swahili chrome around English screens. Adding a locale means adding its
/// `app_<code>.arb` and listing it here.
class AppLocales {
  AppLocales._();

  static const supported = [Locale('en')];

  static const delegates = <LocalizationsDelegate<dynamic>>[
    AppLocalizations.delegate,
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];
}
