import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:get_storage/get_storage.dart';
import 'app/bindings/initial_binding.dart';
import 'app/routes/app_pages.dart';
import 'app/routes/app_routes.dart';
import 'app/theme/app_theme.dart';
import 'core/constants/app_constants.dart';
import 'firebase_options.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await GetStorage.init();

  // Firebase is only initialized outside mock mode. lib/firebase_options.dart
  // was generated by `flutterfire configure` against the sellora-20 project
  // (web + Android are configured; see README.md to add iOS/macOS/Windows/
  // Linux later — DefaultFirebaseOptions.currentPlatform throws on those
  // until then).
  if (!AppConstants.useMockData) {
    await Firebase.initializeApp(
        options: DefaultFirebaseOptions.currentPlatform);
  }

  runApp(const SelloraApp());
}

class SelloraApp extends StatelessWidget {
  const SelloraApp({super.key});

  @override
  Widget build(BuildContext context) {
    return GetMaterialApp(
      title: AppConstants.appName,
      debugShowCheckedModeBanner: false,
      theme: AppTheme.light,
      themeMode: ThemeMode.light,
      // Web opens straight on the marketing/landing page, matching how a
      // browser homepage behaves. Mobile leads with the branded splash,
      // which (once its session check finds nobody signed in) continues to
      // role select and then sign-in — a mobile-app-only affordance, since
      // there's no address bar to hand a first-time visitor a store's URL.
      initialRoute: kIsWeb ? Routes.marketing : Routes.splash,
      initialBinding: InitialBinding(),
      getPages: AppPages.pages,
      defaultTransition: Transition.cupertino,
    );
  }
}
